### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by nicolasmaia** [luke-c/Ikue#2]
It'd be pretty neat to have this on F-Droid, as there is no offline jp dictionaries there: https://f-droid.org/

**Comment by luke-c** [comment]
See issue #1

**Comment by nicolasmaia** [comment]
@izzySoft in the meantime, it might be a good idea to add this to your repo

**Comment by IzzySoft** [comment]
@picsi good idea. But [there's a but](https://apt.izzysoft.de/fdroid/index/info) (not too long, please read for future suggestions – which are always welcome!). To give you an idea: the `.apk` has ~33M. I've limited space per app to 20M (including up to 3 versions). My repo runs on personal space, so space is not an "always given" …

Apart (no blame thrown here, just stating the obvious), the last release in `releases/` was in 3/2017. Reading the linked issue, there's a rework in progress leading to a new version going to F-Droid. As there seem to be no updates before that, I see no reason why it cannot be installed from here if needed (and found, granted).

**Comment by nicolasmaia** [comment]
Fair enough!
